feat: 🎸 allow for skiping affirm for manual execution
PolymeshAssociation/polymesh-sdk pull request #1004
Opened 2023-06-29 17:19 UTC by polymath-eric

### Description

instruction `executeManually` method now accepts `skipAffirmationCheck` param for when it is to be used in a batch

### Breaking Changes

BREAKING CHANGE: 🧨 Instruction `executeManually` requires an arguement

### JIRA Link

[DA-756](https://polymesh.atlassian.net/browse/DA-756)

### Checklist

- [ ] Updated the Readme.md (if required) ?

2023-06-29 17:28 UTC, polymath-eric commented
I made this a breaking change after trying out adding a new endpoint.

I am thinking an integrator using `executeManual` probably wants control, so shouldn't be too inconvenienced at inspecting the call site and deciding on the correct behavior.

By principle I dislike having boolean params that toggle internal logic, but I think this case is worth while making an exception for. `instruction.executeManualButSkipAffirmationCheck` doesn't look good as a name. Having to specify details when opting for manual execution seems reasonable and should be easy to update.

We have a breaking change here, so I am hoping these can go out together since they are both relatively minor: https://github.com/PolymeshAssociation/polymesh-sdk/pull/996

2023-06-30 11:47 UTC, prashantasdeveloper approved these changes

2023-06-30 12:14 UTC, VictorVicente requested changes
Standby to check if this breaking change can be avoided

2023-07-05 18:35 UTC, polymath-eric commented on src/api/procedures/types.ts
> +export interface InstructionIdParams {
I think this is a more accurate name for it. In the affirm method the intent is still clear due to the method name.

2023-07-06 12:20 UTC, merged

2023-07-06 12:41 UTC, prashantasdeveloper commented
:tada: This PR is included in version 21.0.0-alpha.4 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/21.0.0-alpha.4)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v21.0.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-18 15:12 UTC, prashantasdeveloper commented
:tada: This PR is included in version 21.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/21.0.0-beta.1)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v21.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: