fix: 🐛 Use `9.0.1` version for `bignumber.js`
PolymeshAssociation/polymesh-sdk pull request #1040
Opened 2023-09-06 17:10 UTC by prashantasdeveloper

### Description

The `9.1.2` version of `bignumber.js` doesn't export `./bignumber` path in it's package.json file which errors as `Error
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bignumber' is not defined by "exports"`

### Breaking Changes

NA

### JIRA Link

NA

### Checklist

- [ ] Updated the Readme.md (if required) ?

2023-09-06 17:11 UTC, VictorVicente approved these changes

2023-09-06 17:15 UTC, polymath-eric approved these changes

2023-09-06 17:16 UTC, polymath-eric commented
where did you run into this error?

2023-09-06 17:22 UTC, polymath-eric requested changes
lets see if there is a better way than downgrading for now

2023-09-06 17:50 UTC, polymath-eric commented
Seems like the error happens on node `18.13.0` but is OK on node `18.16.0`

Makes sense to downgrade for now so others don't run into this issue

2023-09-06 17:50 UTC, polymath-eric approved these changes

2023-09-07 12:30 UTC, merged

2023-09-07 12:40 UTC, prashantasdeveloper commented
:tada: This PR is included in version 22.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/22.0.1)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v22.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: