feat: 🎸 add `onStatusChange` to confidential transaction
PolymeshAssociation/polymesh-sdk pull request #1122
Opened 2024-01-22 16:04 UTC by polymath-eric

### Description

allows for subscription to confidential transaction status changes

### Breaking Changes

none

### JIRA Link

✅ Closes: [DA-995](https://polymesh.atlassian.net/browse/DA-995)

### Checklist

- [ ] Updated the Readme.md (if required) ?

2024-01-23 07:57 UTC, prashantasdeveloper requested changes

2024-01-23 07:57 UTC, prashantasdeveloper commented on src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
> +    const rawId = dsMockUtils.createMockU64(new BigNumber(1));
nit -> I prefer initializing in the beforeEach/beforeAll section especially the mock values

2024-01-23 07:57 UTC, prashantasdeveloper commented on src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
> +      instructionStatusesMock = dsMockUtils.createQueryMock(
```suggestion
      transactionStatusesMock = dsMockUtils.createQueryMock(
```
nit -> feels like got left over from copy paste

2024-01-23 13:57 UTC, polymath-eric commented on src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
> +      instructionStatusesMock = dsMockUtils.createQueryMock(
😅

2024-01-23 16:54 UTC, prashantasdeveloper approved these changes

2024-01-23 16:54 UTC, merged

2024-02-07 08:24 UTC, prashantasdeveloper commented
:tada: This PR is included in version 24.0.0-confidential-assets.1 :tada:

The release is available on:
- [npm package (@confidential-assets dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/24.0.0-confidential-assets.1)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v24.0.0-confidential-assets.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: