feat: 🎸 add affirm/reject methods for confidential transaction
PolymeshAssociation/polymesh-sdk pull request #1135
Opened 2024-02-06 17:30 UTC by polymath-eric

### Description

also adds `getLegState` and `getLegStates` on confidential transaction to help retrieve proof info

### Breaking Changes

None

### JIRA Link

[DA-982](https://polymesh.atlassian.net/browse/DA-982)

### Checklist

- [ ] Updated the Readme.md (if required) ?

2024-02-06 17:31 UTC, polymath-eric commented on src/api/entities/CheckpointSchedule/index.ts
> + * @hidden
not sure if these are needed, but seems like most Params have them

2024-02-06 17:31 UTC, polymath-eric commented on src/api/entities/Identity/index.ts
> -  ): Promise<ResultSet<ConfidentialAffirmation> | UnsubCallback> {
was copy paste left over from a previous PR 😅

2024-02-06 19:31 UTC, prashantasdeveloper requested changes
Left some nit comments. Also, can you add in the branch name `confidential-assets` in the push branches for github workflows. I missed it in my PR. Merging this PR would trigger a release then

2024-02-06 19:31 UTC, prashantasdeveloper commented on src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
> +  describe('method: affirm', () => {
```suggestion
  describe('method: affirmLeg', () => {
```

2024-02-06 19:31 UTC, prashantasdeveloper commented on src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
> +    jest.spyOn(mockLegReturn, 'unwrap').mockReturnValue(mockLegState);
Why is there a need to spy the unwrap? I think if you set the assetState.toJSON() before initializing the mockLegReturn it could work as expected

2024-02-06 19:31 UTC, prashantasdeveloper commented on src/api/procedures/affirmConfidentialTransactions.ts
> +);
these all needs to be exported and also should be moved to types file to properly work with docs i guess

2024-02-07 08:12 UTC, merged

2024-02-07 08:23 UTC, prashantasdeveloper commented
:tada: This PR is included in version 24.0.0-confidential-assets.1 :tada:

The release is available on:
- [npm package (@confidential-assets dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/24.0.0-confidential-assets.1)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v24.0.0-confidential-assets.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: