feat: 🎸 get assets held by account
PolymeshAssociation/polymesh-sdk pull request #1138
Opened 2024-02-09 08:03 UTC by sansan

### Description

- updates the types for SQ
- adds method to get hel assets

### JIRA Link

https://polymesh.atlassian.net/browse/DA-1035

### Checklist

- [x] Updated the Readme.md (if required) ?

2024-02-09 12:58 UTC, polymath-eric requested changes

2024-02-09 12:58 UTC, polymath-eric commented on src/middleware/queries.ts
> + * Get Confidential Assets hel by a ConfidentialAccount
```suggestion
 * Get Confidential Assets held by a ConfidentialAccount
```

2024-02-09 12:58 UTC, polymath-eric commented on src/api/entities/confidential/ConfidentialAccount/index.ts
> +  public async getHeldAssets(): Promise<string[]> {
```suggestion
  public async getHeldAssets(
    opts: {
      order?: AssetHoldersOrderBy;
      size?: BigNumber;
      start?: BigNumber;
    } = {}
  ): Promise<ResultSet<ConfidentialAsset>> {
```

looking at the Identity signature, I think we should allow pagination options + return the ConfidentialAsset entity

2024-02-10 05:21 UTC, prashantasdeveloper requested changes

2024-02-10 05:21 UTC, prashantasdeveloper commented on src/middleware/queries.ts
> +        orderBy: [${TickerExternalAgentHistoriesOrderBy.CreatedAtAsc}, ${TickerExternalAgentHistoriesOrderBy.CreatedBlockIdAsc}]
It seems this got left over from copy paste

2024-02-16 17:23 UTC, polymath-eric approved these changes

2024-02-16 17:23 UTC, polymath-eric commented on src/api/entities/confidential/ConfidentialAccount/index.ts
> +   *
```suggestion
```

2024-02-16 17:23 UTC, polymath-eric commented on src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts
> +      const asset = new ConfidentialAsset({ id: assetId }, context);
I think SDK uses `entityMockUtils.getConfidentialAsset()` type methods, but seems like a real one works here.

2024-02-16 17:24 UTC, polymath-eric commented
left 2 nits, but otherwise lgtm

2024-02-16 18:07 UTC, merged

2024-02-16 18:19 UTC, prashantasdeveloper commented
:tada: This PR is included in version 24.0.0-confidential-assets.3 :tada:

The release is available on:
- [npm package (@confidential-assets dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/24.0.0-confidential-assets.3)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v24.0.0-confidential-assets.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: