fix: 🐛 Validate primary key on `modifySignerPermissions`
PolymeshAssociation/polymesh-sdk pull request #761
Opened 2022-06-01 18:55 UTC by prashantasdeveloper

### Description

Added validation that the signing Account should be the primary Account of the Identity in `modifySignerPermissions` procedure

### Breaking Changes

🧨 `accountManagement.modifyPermissions` and `accountManagement.revokePermissions`
 now throw an error if the signing Account is not the primary Account of the Identity
 whose secondary Accounts' permissions are modified/revoked

### JIRA Link

DA-308

### Checklist

- [ ] Updated the Readme.md (if required) ?

2022-06-02 14:08 UTC, VictorVicente commented
> Sonar says the following in the procedure methods
> 
> > Remove the unused function parameter "this" or rename it to "_this" to make intention explicit.
> 
> I think this is something which @polymath-eric also faced once. Probably to be marked as false positive. @monitz87 can you help here?

Solved!

2022-06-02 14:33 UTC, monitz87 requested changes

2022-06-02 14:33 UTC, monitz87 commented on src/AccountManagement.ts
> +   * @throws if signing Account is not the primary Account of the Identity whose secondary Accounts' permissions are being revoked
```suggestion
   * @throws if the signing Account is not the primary Account of the Identity whose secondary Account permissions are being revoked
```

2022-06-02 14:33 UTC, monitz87 commented on src/AccountManagement.ts
> +   * @throws if signing Account is not the primary Account of the Identity whose secondary Accounts' permissions are being modified
```suggestion
   * @throws if the signing Account is not the primary Account of the Identity whose secondary Account permissions are being modified
```

2022-06-02 19:50 UTC, VictorVicente approved these changes

2022-06-02 19:50 UTC, merged

2022-06-02 20:05 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.9 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.9)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-06-10 18:07 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-alpha.11 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0-alpha.11)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-12 19:11 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-10 17:02 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v15.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: