fix: 🐛 Handle NoData claimType in conversion util
PolymeshAssociation/polymesh-sdk pull request #768
Opened 2022-06-02 19:57 UTC by polymath-eric

### Description

`sdk.claims.getTargetingClaims()` was throwing an error due to iterating on ClaimType and passing to createType.

We need to keep NoData around, since Middleware uses it, but in createType, we can only pass on or the other.

They are equivalent in function so this should be OK, although its a bit messy.

### Breaking Changes

### JIRA Link

### Checklist

- [ ] Updated the Readme.md (if required) ?

2022-06-03 05:01 UTC, prashantasdeveloper approved these changes
LGTM. If you could add a small test for this that would be great

2022-06-03 15:30 UTC, monitz87 requested changes

2022-06-03 15:30 UTC, monitz87 commented on src/utils/__tests__/conversion.ts
> +    it('should convert a ClaimType to a polkadot Claim', () => {
```suggestion
    it('should convert a ClaimType to a polkadot ClaimType', () => {
```

2022-06-06 12:51 UTC, VictorVicente approved these changes

2022-06-06 12:52 UTC, merged

2022-06-06 13:13 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-alpha.5 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/15.0.0-alpha.5)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-alpha.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-12 19:11 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-10 17:01 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v15.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: